USE [master]
GO

/****** Object:  Database [MyDatabaseSQLServer]    Script Date: 20.06.2024 15:16:18 ******/
CREATE DATABASE [MyDatabaseSQLServer]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyDatabaseSQLServe', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MyDatabaseSQLServe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyDatabaseSQLServe_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MyDatabaseSQLServe_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyDatabaseSQLServer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyDatabaseSQLServer] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET  MULTI_USER 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyDatabaseSQLServer] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyDatabaseSQLServer] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MyDatabaseSQLServer] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MyDatabaseSQLServer] SET  READ_WRITE 
GO

